### ISSUE TITLE
Consolidate dependencies to npm

### ISSUE THREAD

**Issue by meandavejustice** [crashspringfield/camover#1]
All of these dependencies can be installed from npm, I would suggest only using one package manager to simplify installs and setup.
```
    "angular-ui-router": "ui-router#^0.3.2",
    "angular": "^1.5.8",
    "bootstrap": "^3.3.7",
    "ngmap": "^1.17.8",
    "components-font-awesome": "^4.7.0"
```

**Comment by matthewboman** [comment]
Sometimes I see front end divided out into a bower.json and the back end in the package.json. It that a waste or useful to keep it clear?
