### ISSUE TITLE
deprecation warning from mongoosejs

### ISSUE THREAD

**Issue by meandavejustice** [crashspringfield/camover#2]
You should be able to use es6 Promises depending so long as you are on current node version.
```
(node:27181) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated,
plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
```

**Comment by matthewboman** [comment]
I was using Mongoose for the camera database and Mongoskin for the users database, so I just switched it out and now use Mongoskin for both.
